manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 11808e9ea8abc132661fe18a21236e053ab04b93
      import: true

  self:
    path: zephcore
