manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 3e8f38faf93704249745dbc475052848ce39fdaf
      import: true

  self:
    path: zephcore
